/**
 * @file test_frequency.cpp
 * @brief Unit tests for frequency.h (.bed/.bim/.frq I/O)
 *
 * Requires test data generated by generate_test_data.
 */

#include "test_harness.h"
#include "frequency.h"
#include <cmath>
#include <fstream>
#include <sys/stat.h>

static const std::string DATA_DIR = "tests/data";
static const std::string PREFIX   = "tests/data/test";

static bool data_exists() {
    struct stat st;
    return (stat((PREFIX + ".bed").c_str(), &st) == 0);
}

TEST_CASE(load_bim_snps) {
    if (!data_exists()) { std::cerr << "  SKIP: no test data\n"; return; }

    auto snps = fastlckin::load_bim_snps(PREFIX + ".bim");
    CHECK(snps.size() == 50);
    CHECK(snps[0].chrom == "chr1");
    CHECK(!snps[0].ref.empty());
    CHECK(!snps[0].alt.empty());
    CHECK(snps[0].pos == 10000);
    CHECK(snps[49].pos == 59000);
}

TEST_CASE(read_bed_genotypes) {
    if (!data_exists()) { std::cerr << "  SKIP: no test data\n"; return; }

    std::vector<int> indices = {0, 1, 2, 3, 4};
    auto geno = fastlckin::read_bed_genotypes(
        PREFIX + ".bed", PREFIX + ".bim", indices);

    CHECK(geno.size() == 20);  // 20 samples
    CHECK(geno[0].size() == 5);  // 5 SNPs

    // All values should be 0, 1, or 2 (or -1 for missing)
    for (size_t i = 0; i < geno.size(); ++i) {
        for (size_t j = 0; j < geno[i].size(); ++j) {
            CHECK(geno[i][j] >= -1 && geno[i][j] <= 2);
        }
    }
}

TEST_CASE(compute_allele_frequencies_from_bed) {
    if (!data_exists()) { std::cerr << "  SKIP: no test data\n"; return; }

    std::vector<int> all_indices;
    auto snps = fastlckin::load_bim_snps(PREFIX + ".bim");
    for (int i = 0; i < static_cast<int>(snps.size()); ++i) all_indices.push_back(i);

    auto freqs = fastlckin::compute_allele_frequencies(
        PREFIX + ".bed", PREFIX + ".bim", all_indices);

    CHECK(freqs.size() == 50);
    for (size_t i = 0; i < freqs.size(); ++i) {
        CHECK(freqs[i] >= 0.0 && freqs[i] <= 1.0);
    }
}

TEST_CASE(read_plink_freq) {
    if (!data_exists()) { std::cerr << "  SKIP: no test data\n"; return; }

    auto snps = fastlckin::load_bim_snps(PREFIX + ".bim");
    auto freqs = fastlckin::read_plink_freq(PREFIX + ".frq", snps);

    CHECK(freqs.size() == 50);
    int matched = 0;
    for (size_t i = 0; i < freqs.size(); ++i) {
        if (freqs[i] >= 0.0 && freqs[i] <= 1.0) ++matched;
    }
    CHECK(matched > 0);  // At least some should match
}

int main() {
    return RUN_ALL_TESTS();
}
