/**
 * @file test_input_modes.cpp
 * @brief End-to-end tests for all three input modes (VCF-only, VCF+PLINK, PLINK-only)
 *
 * Requires test data generated by generate_test_data (tests/data/test.*)
 */

#include "test_harness.h"
#include "kinship_estimator.h"
#include <cmath>
#include <vector>
#include <fstream>
#include <sys/stat.h>

using namespace fastlckin;

// Check that test data exists
static bool test_data_exists() {
    struct stat st;
    return (stat("tests/data/test.vcf", &st) == 0 &&
            stat("tests/data/test.bed", &st) == 0 &&
            stat("tests/data/test.bim", &st) == 0 &&
            stat("tests/data/test.fam", &st) == 0);
}

TEST_CASE(mode2_vcf_plink_runs) {
    // Mode 2 (VCF+PLINK) should produce valid results
    if (!test_data_exists()) {
        std::cerr << "  SKIP: test data not found (run generate_test_data first)\n";
        return;
    }

    KinshipConfig config;
    config.vcf_path = "tests/data/test.vcf";
    config.plink_prefix = "tests/data/test";
    config.input_mode = InputMode::VCF_PLINK;
    config.output_path = "/tmp/test_mode2_output.tsv";
    config.classify = true;

    KinshipEstimator estimator(config);
    auto results = estimator.run();

    // 20 samples → C(20,2) = 190 pairs
    CHECK(results.size() == 190);

    // All results should have valid IBD coefficients
    for (const auto& r : results) {
        CHECK(!r.failed);
        CHECK(r.k0 >= 0.0 && r.k0 <= 1.0);
        CHECK(r.k1 >= 0.0 && r.k1 <= 1.0);
        CHECK(r.k2 >= 0.0 && r.k2 <= 1.0);
        CHECK_NEAR(r.k0 + r.k1 + r.k2, 1.0, 0.01);
        CHECK(r.pi_hat >= 0.0 && r.pi_hat <= 1.0);
        CHECK(r.n_snps > 0);
    }
}

TEST_CASE(mode1_vcf_only_runs) {
    // Mode 1 (VCF-only) should produce valid results
    if (!test_data_exists()) {
        std::cerr << "  SKIP: test data not found\n";
        return;
    }

    KinshipConfig config;
    config.vcf_path = "tests/data/test.vcf";
    config.input_mode = InputMode::VCF_ONLY;
    config.output_path = "/tmp/test_mode1_output.tsv";
    config.classify = true;

    KinshipEstimator estimator(config);
    auto results = estimator.run();

    CHECK(results.size() == 190);

    for (const auto& r : results) {
        CHECK(!r.failed);
        CHECK(r.k0 >= 0.0 && r.k0 <= 1.0);
        CHECK(r.k1 >= 0.0 && r.k1 <= 1.0);
        CHECK(r.k2 >= 0.0 && r.k2 <= 1.0);
        CHECK_NEAR(r.k0 + r.k1 + r.k2, 1.0, 0.01);
    }
}

TEST_CASE(mode3_plink_only_runs) {
    // Mode 3 (PLINK-only) should produce valid results
    if (!test_data_exists()) {
        std::cerr << "  SKIP: test data not found\n";
        return;
    }

    KinshipConfig config;
    config.plink_prefix = "tests/data/test";
    config.input_mode = InputMode::PLINK_ONLY;
    config.output_path = "/tmp/test_mode3_output.tsv";
    config.classify = true;

    KinshipEstimator estimator(config);
    auto results = estimator.run();

    CHECK(results.size() == 190);

    for (const auto& r : results) {
        CHECK(!r.failed);
        CHECK(r.k0 >= 0.0 && r.k0 <= 1.0);
        CHECK(r.k1 >= 0.0 && r.k1 <= 1.0);
        CHECK(r.k2 >= 0.0 && r.k2 <= 1.0);
        CHECK_NEAR(r.k0 + r.k1 + r.k2, 1.0, 0.01);
    }
}

TEST_CASE(modes_produce_similar_unrelated) {
    // For random unrelated samples, all modes should give PI_HAT close to 0
    if (!test_data_exists()) {
        std::cerr << "  SKIP: test data not found\n";
        return;
    }

    // Run Mode 1
    KinshipConfig c1;
    c1.vcf_path = "tests/data/test.vcf";
    c1.input_mode = InputMode::VCF_ONLY;
    c1.output_path = "/tmp/test_cmp_mode1.tsv";

    KinshipEstimator e1(c1);
    auto r1 = e1.run();

    // Run Mode 3
    KinshipConfig c3;
    c3.plink_prefix = "tests/data/test";
    c3.input_mode = InputMode::PLINK_ONLY;
    c3.output_path = "/tmp/test_cmp_mode3.tsv";

    KinshipEstimator e3(c3);
    auto r3 = e3.run();

    CHECK(r1.size() == r3.size());

    // Both should give low PI_HAT for random data (majority of pairs)
    double mean_pi1 = 0.0, mean_pi3 = 0.0;
    for (const auto& r : r1) mean_pi1 += std::abs(r.pi_hat);
    for (const auto& r : r3) mean_pi3 += std::abs(r.pi_hat);
    mean_pi1 /= r1.size();
    mean_pi3 /= r3.size();

    // Mean |PI_HAT| should be reasonable for random samples
    // Note: with only 50 SNPs, MLE variance is very high — this is a
    // smoke test to verify the pipeline runs, not a statistical test
    CHECK(mean_pi1 < 0.8);
    CHECK(mean_pi3 < 0.5);
}

TEST_CASE(output_mode_header) {
    // Verify the output file contains the mode indicator
    if (!test_data_exists()) {
        std::cerr << "  SKIP: test data not found\n";
        return;
    }

    KinshipConfig config;
    config.vcf_path = "tests/data/test.vcf";
    config.input_mode = InputMode::VCF_ONLY;
    config.output_path = "/tmp/test_header_check.tsv";

    KinshipEstimator estimator(config);
    estimator.run();

    // Read first few lines of output
    std::ifstream ifs("/tmp/test_header_check.tsv");
    CHECK(ifs.is_open());

    std::string line;
    bool found_mode = false;
    for (int i = 0; i < 5 && std::getline(ifs, line); ++i) {
        if (line.find("# Mode: VCF-only") != std::string::npos) {
            found_mode = true;
            break;
        }
    }
    CHECK(found_mode);
}

TEST_CASE(input_mode_names) {
    CHECK(std::string(input_mode_name(InputMode::VCF_ONLY)) == "VCF-only");
    CHECK(std::string(input_mode_name(InputMode::VCF_PLINK)) == "VCF+PLINK");
    CHECK(std::string(input_mode_name(InputMode::PLINK_ONLY)) == "PLINK-only");
}

TEST_CASE(no_ld_prune_skip_flag) {
    // With --no-ld-prune, all unmasked SNPs should be used and pipeline should succeed
    if (!test_data_exists()) {
        std::cerr << "  SKIP: test data not found\n";
        return;
    }

    // Run Mode 3 with LD pruning skipped
    KinshipConfig config;
    config.plink_prefix = "tests/data/test";
    config.input_mode = InputMode::PLINK_ONLY;
    config.output_path = "/tmp/test_no_ld_prune.tsv";
    config.ld_config.skip = true;

    KinshipEstimator estimator(config);
    auto results = estimator.run();

    CHECK(results.size() == 190);

    for (const auto& r : results) {
        CHECK(!r.failed);
        CHECK(r.n_snps > 0);
        CHECK(r.k0 >= 0.0 && r.k0 <= 1.0);
        CHECK(r.k1 >= 0.0 && r.k1 <= 1.0);
        CHECK(r.k2 >= 0.0 && r.k2 <= 1.0);
        CHECK_NEAR(r.k0 + r.k1 + r.k2, 1.0, 0.01);
    }

    // Verify the output header contains "skipped"
    std::ifstream ifs("/tmp/test_no_ld_prune.tsv");
    CHECK(ifs.is_open());
    std::string line;
    bool found_skipped = false;
    for (int i = 0; i < 6 && std::getline(ifs, line); ++i) {
        if (line.find("LD_prune: skipped") != std::string::npos) {
            found_skipped = true;
            break;
        }
    }
    CHECK(found_skipped);
}

TEST_CASE(no_ld_prune_retains_more_snps) {
    // With --no-ld-prune, N_SNPs should be >= LD-pruned version
    if (!test_data_exists()) {
        std::cerr << "  SKIP: test data not found\n";
        return;
    }

    // Run with LD pruning (default)
    KinshipConfig c_ld;
    c_ld.plink_prefix = "tests/data/test";
    c_ld.input_mode = InputMode::PLINK_ONLY;
    c_ld.output_path = "/tmp/test_ld_on.tsv";
    KinshipEstimator e_ld(c_ld);
    auto r_ld = e_ld.run();

    // Run without LD pruning
    KinshipConfig c_nold;
    c_nold.plink_prefix = "tests/data/test";
    c_nold.input_mode = InputMode::PLINK_ONLY;
    c_nold.output_path = "/tmp/test_ld_off.tsv";
    c_nold.ld_config.skip = true;
    KinshipEstimator e_nold(c_nold);
    auto r_nold = e_nold.run();

    CHECK(r_ld.size() == r_nold.size());

    // No-LD should retain >= LD-pruned SNPs for each pair
    int n_more = 0, n_equal = 0;
    for (size_t i = 0; i < r_ld.size(); ++i) {
        if (r_nold[i].n_snps > r_ld[i].n_snps) ++n_more;
        else if (r_nold[i].n_snps == r_ld[i].n_snps) ++n_equal;
    }
    // At least some pairs should have more SNPs without LD pruning
    CHECK(n_more + n_equal == static_cast<int>(r_ld.size()));
}

int main() {
    return RUN_ALL_TESTS();
}
