/**
 * @file test_genotype_likelihood.cpp
 * @brief Unit tests for genotype_likelihood.h (PL/GL extraction from VCF)
 *
 * Requires test data generated by generate_test_data.
 */

#include "test_harness.h"
#include "genotype_likelihood.h"
#include "io/vcf.h"
#include <cmath>
#include <sys/stat.h>

static const std::string VCF_PATH = "tests/data/test.vcf";

static bool data_exists() {
    struct stat st;
    return (stat(VCF_PATH.c_str(), &st) == 0);
}

TEST_CASE(extract_pl_from_vcf) {
    if (!data_exists()) { std::cerr << "  SKIP: no test data\n"; return; }

    ngslib::VCFFile vcf(VCF_PATH, "r");
    auto& hdr = vcf.header();
    int n_samples = hdr.n_samples();
    CHECK(n_samples == 20);

    ngslib::VCFRecord rec;
    int status = vcf.read(rec);
    CHECK(status >= 0);

    rec.unpack(BCF_UN_FMT);
    auto gls = fastlckin::extract_genotype_likelihoods(rec, hdr, n_samples, 1);

    CHECK(static_cast<int>(gls.size()) == n_samples);

    // Check that at least some samples have valid GLs
    int valid_count = 0;
    for (const auto& gl : gls) {
        if (!gl.masked) {
            ++valid_count;
            // GLs should be positive linear values
            CHECK(gl.gl[0] > 0.0);
            CHECK(gl.gl[1] > 0.0);
            CHECK(gl.gl[2] > 0.0);
            // GQ should be non-negative
            CHECK(gl.gq >= 0);
        }
    }
    CHECK(valid_count > 0);
}

TEST_CASE(extract_pl_likelihood_ordering) {
    if (!data_exists()) { std::cerr << "  SKIP: no test data\n"; return; }

    ngslib::VCFFile vcf(VCF_PATH, "r");
    auto& hdr = vcf.header();
    int n_samples = hdr.n_samples();

    ngslib::VCFRecord rec;
    vcf.read(rec);
    rec.unpack(BCF_UN_FMT);
    auto gls = fastlckin::extract_genotype_likelihoods(rec, hdr, n_samples, 1);

    // For each valid sample, check that the best GL is highest
    for (const auto& gl : gls) {
        if (gl.masked) continue;
        double max_gl = std::max({gl.gl[0], gl.gl[1], gl.gl[2]});
        CHECK(max_gl > 0.0);
    }
}

TEST_CASE(extract_all_snps) {
    if (!data_exists()) { std::cerr << "  SKIP: no test data\n"; return; }

    ngslib::VCFFile vcf(VCF_PATH, "r");
    auto& hdr = vcf.header();
    int n_samples = hdr.n_samples();

    int snp_count = 0;
    ngslib::VCFRecord rec;
    while (vcf.read(rec) >= 0) {
        rec.unpack(BCF_UN_FMT);
        auto gls = fastlckin::extract_genotype_likelihoods(rec, hdr, n_samples, 1);
        CHECK(static_cast<int>(gls.size()) == n_samples);
        ++snp_count;
    }
    CHECK(snp_count == 50);
}

TEST_CASE(gq_filter_masks) {
    if (!data_exists()) { std::cerr << "  SKIP: no test data\n"; return; }

    ngslib::VCFFile vcf(VCF_PATH, "r");
    auto& hdr = vcf.header();
    int n_samples = hdr.n_samples();

    ngslib::VCFRecord rec;
    vcf.read(rec);
    rec.unpack(BCF_UN_FMT);

    // With very high GQ threshold, most should be masked
    auto gls_strict = fastlckin::extract_genotype_likelihoods(rec, hdr, n_samples, 99);
    auto gls_loose = fastlckin::extract_genotype_likelihoods(rec, hdr, n_samples, 0);

    int masked_strict = 0, masked_loose = 0;
    for (const auto& gl : gls_strict) if (gl.masked) ++masked_strict;
    for (const auto& gl : gls_loose) if (gl.masked) ++masked_loose;

    CHECK(masked_strict >= masked_loose);
}

int main() {
    return RUN_ALL_TESTS();
}
